name: charla
on: [push,pull_request]
jobs:
  build: 
    runs-on: ubuntu_latest 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      working-directory: ./demo
      run: mvn compile --file pom.xml